name: Notify failure
description: Notify failure
inputs:
  outputs:
    description: |
      Prepare action's outputs
    required: true
  pull_request_comment:
    description: |
      Pull Request comment
    required: false
    default: |
      :x: Securefix failed.
runs:
  using: composite
  steps:
    # Create a pull request comment to report an error
    - if: fromJson(inputs.outputs).pull_request_number != ''
      shell: bash
      env:
        GH_TOKEN: ${{fromJson(inputs.outputs).github_token}}
        REPO: ${{ fromJson(inputs.outputs).repository_full_name }}
        PR_NUMBER: ${{ fromJson(inputs.outputs).pull_request_number }}
        COMMENT: |
          ${{ inputs.pull_request_comment }}
          [Workflow](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})
          The comment was created by [Securefix Action](https://github.com/securefix-action/action).
      run: |
        gh pr comment \
          -R "$REPO" \
          -b "${COMMENT}" \
          "$PR_NUMBER"
