name: JavaScript Action
description: JavaScript Action
inputs:
  config:
    description: config
    required: false
  metadata:
    description: metadata
    required: true
  repository:
    description: repository
    required: true
  branch:
    description: branch
    required: true
outputs: {}
runs:
  using: node20
  main: dist/index.js
