name: JavaScript Action
description: JavaScript Action
inputs:
  action:
    description: config
    required: true
  config:
    description: config
    required: false
  config_file:
    description: File path to the config file
    required: false

  root_dir:
    description: Root directory to be pushed
    required: false

  files:
    description: |
      Fixed files
    required: false

  metadata_file:
    description: metadata file path
    required: false
  changed_files:
    description: A file that changed files are listed in
    required: false
  github_token:
    description: A GitHub access token
    required: false
  run_id:
    description: A workflow run id
    required: false
  allow_workflow_fix:
    description: |
      Either true or false. If true, the action allows the workflow to fix the code.
    required: false
    default: "false"
  workflow_name:
    description: |
      Client Workflow name. If this is empty, the action does not check the workflow name.
    required: false
    default: securefix
outputs: {}
runs:
  using: node20
  main: dist/index.js
