name: Fix Code securely
description: Fix Code securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository:
    description: |
      Server repository name
    required: false
    default: securefix
  commit_message:
    description: |
      Commit message
    required: false
  files:
    description: |
      Fixed files
    required: false
  fail_if_changes:
    description: |
      If true, the action fails if there are changes.
    required: false
  repository:
    description: |
      A repository full name where a commit will be pushed.
    required: false
  branch:
    description: |
      A branch where a commit will be pushed.
    required: false
  root_dir:
    description: |
      A Git root directory where a commit will be pushed.
    required: false
  pull_request_title:
    description: |
      A pull request title.
      To create a pull request, this is required.
    required: false
  pull_request_base_branch:
    description: |
      A pull request base branch.
      To create a pull request, this is required.
    required: false
  pull_request_body:
    description: |
      A pull request body.
    required: false
  pull_request_labels:
    description: |
      Pull request labels.
      This requires the `issues:write` permission.
    required: false
  pull_request_draft:
    description: |
      Create a pull request as draft.
    required: false
  pull_request_reviewers:
    description: |
      Pull request reviewers.
    required: false
  pull_request_team_reviewers:
    description: |
      Pull request team reviewers.
      This requires the `members:read` permission.
    required: false
  pull_request_assignees:
    description: |
      Pull request assignees.
    required: false
  pull_request_comment:
    description: |
      Pull request comment.
      If this is set, a pull request comment is posted after a pull request is created.
    required: false
  project_owner:
    description: |
      Project owner where the pull request is added.
    required: false
  project_number:
    description: |
      Project number where the pull request is added.
    required: false
  milestone_number:
    description: |
      Milestone number where the pull request is added.
    required: false
runs:
  using: composite
  steps:
    - uses: csm-actions/securefix-action/js@f0512b1d3339d392afed8ecc839c96b62a8da9a9
      id: client1
      with:
        action: client1
        files: ${{inputs.files}}
        root_dir: ${{inputs.root_dir}}

    # Create a GitHub App token to create and delete a label
    - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      if: steps.client1.outputs.changed_files != ''
      id: token
      with:
        app-id: ${{inputs.app_id}}
        private-key: ${{inputs.app_private_key}}
        owner: ${{github.repository_owner}}
        repositories: ${{inputs.server_repository}}
        permission-issues: write

    # Create metadata
    - if: steps.client1.outputs.changed_files != ''
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: metadata
      env:
        COMMIT_MESSAGE: ${{inputs.commit_message}}
        REPO: ${{inputs.repository}}
        BRANCH: ${{inputs.branch}}
        ROOT_DIR: ${{inputs.root_dir}}
        PR_TITLE: ${{inputs.pull_request_title}}
        PR_BASE_BRANCH: ${{inputs.pull_request_base_branch}}
        PR_BODY: ${{inputs.pull_request_body}}
        PR_LABELS: ${{inputs.pull_request_labels}}
        PR_ASSIGNEES: ${{inputs.pull_request_assignees}}
        PR_REVIEWERS: ${{inputs.pull_request_reviewers}}
        PR_TEAM_REVIEWERS: ${{inputs.pull_request_team_reviewers}}
        PR_DRAFT: ${{inputs.pull_request_draft}}
        PR_COMMENT: ${{inputs.pull_request_comment}}
        PROJECT_OWNER: ${{inputs.project_owner}}
        PROJECT_NUMBER: ${{inputs.project_number}}
        MILESTONE_NUMBER: ${{inputs.milestone_number}}
      with:
        script: |
          if (!process.env.PR_TITLE && (process.env.PR_BASE_BRANCH || process.env.PR_BODY || process.env.PR_LABELS || process.env.PR_ASSIGNEES || process.env.PR_REVIEWERS || process.env.PR_TEAM_REVIEWERS || process.env.PR_DRAFT || process.env.PR_COMMENT)) {
            throw new Error('pull_request_title is required to create a pull request');
          }
          return {
            context: context,
            inputs: {
              repository: process.env.REPO || '',
              branch: process.env.BRANCH || '',
              commit_message: process.env.COMMIT_MESSAGE || '',
              root_dir: process.env.ROOT_DIR || '',
              pull_request: {
                title: process.env.PR_TITLE || '',
                body: process.env.PR_BODY || '',
                base: process.env.PR_BASE_BRANCH || '',
                labels: process.env.PR_LABELS ? process.env.PR_LABELS.trim().split('\n') : [],
                assignees: process.env.PR_ASSIGNEES ? process.env.PR_ASSIGNEES.trim().split('\n') : [],
                reviewers: process.env.PR_REVIEWERS ? process.env.PR_REVIEWERS.trim().split('\n') : [],
                team_reviewers: process.env.PR_TEAM_REVIEWERS ? process.env.PR_TEAM_REVIEWERS.trim().split('\n') : [],
                draft: process.env.PR_DRAFT === 'true',
                comment: process.env.PR_COMMENT || '',
                project: process.env.PROJECT_NUMBER ? {
                  number: parseInt(process.env.PROJECT_NUMBER, 10),
                  owner: process.env.PROJECT_OWNER,
                } : null,
                milestone_number: process.env.MILESTONE_NUMBER ? parseInt(process.env.MILESTONE_NUMBER, 10) : 0,
              }
            },
          };

    # Create a metadata file
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      run: echo "$EVENT" > "${ARTIFACT_NAME}.json"
      env:
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
        EVENT: ${{steps.metadata.outputs.result}}

    # Create a file where fixed file paths are listed
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      run: echo "$FILES" > "${ARTIFACT_NAME}_files.txt"
      env:
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
        FILES: ${{ steps.client1.outputs.changed_files_from_root_dir }}
    # Upload files to GitHub Actions Artifact
    - if: steps.client1.outputs.changed_files != ''
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{steps.client1.outputs.artifact_name}}
        include-hidden-files: true
        path: |
          ${{ steps.client1.outputs.changed_files }}
          ${{steps.client1.outputs.artifact_name}}.json
          ${{steps.client1.outputs.artifact_name}}_files.txt
    # Delete metadata files
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      run: rm "${ARTIFACT_NAME}.json" "${ARTIFACT_NAME}_files.txt"
      env:
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
    # Create a label
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      env:
        GH_TOKEN: ${{ steps.token.outputs.token }}
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
        REPO: ${{inputs.server_repository}}
      run: |
        gh label create \
          -R "${GITHUB_REPOSITORY_OWNER}/${REPO}" \
          "$ARTIFACT_NAME" \
          --description "$GITHUB_REPOSITORY/${GITHUB_RUN_ID}"
    # Fail if changes are detected
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      env:
        FILES: ${{ steps.client1.outputs.changed_files }}
        FAILED: ${{inputs.fail_if_changes != '' && inputs.fail_if_changes || (inputs.repository == '' && inputs.branch == '')}}
      run: |
        if [ "$FAILED" = true ]; then
          echo "::error:: Changes detected. A commit will be pushed"
          echo "$FILES"
          exit 1
        fi
        echo "::notice:: Changes detected. A commit will be pushed"
        echo "$FILES"
