name: Fix Code securely
description: Fix Code securely
author: Shunsuke Suzuki
branding:
  icon: git-commit
  color: green
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository:
    description: |
      Server repository name
    required: false
    default: securefix
  commit_message:
    description: |
      Commit message
    required: false
  files:
    description: |
      Fixed files
    required: false
  fail_if_changes:
    description: |
      If true, the action fails if there are changes.
    required: false
  repository:
    description: |
      A repository full name where a commit will be pushed.
    required: false
  branch:
    description: |
      A branch where a commit will be pushed.
    required: false
  root_dir:
    description: |
      A Git root directory where a commit will be pushed.
    required: false
  pull_request_title:
    description: |
      A pull request title.
      To create a pull request, this is required.
    required: false
  pull_request_base_branch:
    description: |
      A pull request base branch.
      To create a pull request, this is required.
    required: false
  pull_request_body:
    description: |
      A pull request body.
    required: false
  pull_request_labels:
    description: |
      Pull request labels.
      This requires the `issues:write` permission.
    required: false
  pull_request_draft:
    description: |
      Create a pull request as draft.
    required: false
  pull_request_reviewers:
    description: |
      Pull request reviewers.
    required: false
  pull_request_team_reviewers:
    description: |
      Pull request team reviewers.
      This requires the `members:read` permission.
    required: false
  pull_request_assignees:
    description: |
      Pull request assignees.
    required: false
  pull_request_comment:
    description: |
      Pull request comment.
      If this is set, a pull request comment is posted after a pull request is created.
    required: false
  project_owner:
    description: |
      Project owner where the pull request is added.
    required: false
  project_number:
    description: |
      Project number where the pull request is added.
    required: false
  milestone_number:
    description: |
      Milestone number where the pull request is added.
    required: false
  automerge_method:
    description: |
      auto-merge method. One of "merge", "squash", or "rebase".
      By default, auto-merge is disabled.
    required: false
runs:
  using: composite
  steps:
    - uses: csm-actions/securefix-action/js@main
      id: client1
      with:
        action: client1
        files: ${{inputs.files}}
        root_dir: ${{inputs.root_dir}}
        automerge_method: ${{inputs.automerge_method}}
        repository: ${{inputs.repository}}
        branch: ${{inputs.branch}}
        commit_message: ${{inputs.commit_message}}
        pull_request_title: ${{inputs.pull_request_title}}
        pull_request_base_branch: ${{inputs.pull_request_base_branch}}
        pull_request_body: ${{inputs.pull_request_body}}
        pull_request_labels: ${{inputs.pull_request_labels}}
        pull_request_draft: ${{inputs.pull_request_draft}}
        pull_request_reviewers: ${{inputs.pull_request_reviewers}}
        pull_request_team_reviewers: ${{inputs.pull_request_team_reviewers}}
        pull_request_assignees: ${{inputs.pull_request_assignees}}
        pull_request_comment: ${{inputs.pull_request_comment}}
        project_owner: ${{inputs.project_owner}}
        project_number: ${{inputs.project_number}}
        milestone_number: ${{inputs.milestone_number}}

    # Create a file where fixed file paths are listed
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      run: echo "$FILES" > "${ARTIFACT_NAME}_files.txt"
      env:
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
        FILES: ${{ steps.client1.outputs.changed_files_from_root_dir }}
    # Upload files to GitHub Actions Artifact
    - if: steps.client1.outputs.changed_files != ''
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{steps.client1.outputs.artifact_name}}
        include-hidden-files: true
        path: |
          ${{ steps.client1.outputs.changed_files }}
          ${{steps.client1.outputs.artifact_name}}.json
          ${{steps.client1.outputs.artifact_name}}_files.txt
    # Delete metadata files
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      run: rm "${ARTIFACT_NAME}.json" "${ARTIFACT_NAME}_files.txt"
      env:
        ARTIFACT_NAME: ${{ steps.client1.outputs.artifact_name }}
    # Create a label
    - if: steps.client1.outputs.changed_files != ''
      uses: csm-actions/securefix-action/js@main
      with:
        action: create-label
        app_id: ${{inputs.app_id}}
        app_private_key: ${{inputs.app_private_key}}
        server_repository: ${{inputs.server_repository}}
        label: ${{ steps.client1.outputs.artifact_name }}

    # Fail if changes are detected
    - if: steps.client1.outputs.changed_files != ''
      shell: bash
      env:
        FILES: ${{ steps.client1.outputs.changed_files }}
        FAILED: ${{inputs.fail_if_changes != '' && inputs.fail_if_changes || (inputs.repository == '' && inputs.branch == '')}}
      run: |
        if [ "$FAILED" = true ]; then
          echo "::error:: Changes detected. A commit will be pushed"
          echo "$FILES"
          exit 1
        fi
        echo "::notice:: Changes detected. A commit will be pushed"
        echo "$FILES"
