name: JavaScript Action
description: JavaScript Action
inputs:
  action:
    description: config
    required: true
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  server_repository:
    description: |
      Server repository name
    required: true

  commit_message:
    description: |
      Commit message
    required: false
  files:
    description: |
      Fixed files
    required: false
  fail_if_changes:
    description: |
      If true, the action fails if there are changes.
    required: false
    default: "false"
  repository:
    description: |
      A repository full name where a commit will be pushed.
    required: false
  branch:
    description: |
      A branch where a commit will be pushed.
    required: false
  root_dir:
    description: |
      A Git root directory where a commit will be pushed.
    required: false
  pull_request_title:
    description: |
      A pull request title.
      To create a pull request, this is required.
    required: false
  pull_request_base_branch:
    description: |
      A pull request base branch.
      To create a pull request, this is required.
    required: false
  pull_request_body:
    description: |
      A pull request body.
    required: false
  pull_request_labels:
    description: |
      Pull request labels.
      This requires the `issues:write` permission.
    required: false
  pull_request_draft:
    description: |
      Create a pull request as draft.
    required: false
  pull_request_reviewers:
    description: |
      Pull request reviewers.
    required: false
  pull_request_team_reviewers:
    description: |
      Pull request team reviewers.
      This requires the `members:read` permission.
    required: false
  pull_request_assignees:
    description: |
      Pull request assignees.
    required: false
  pull_request_comment:
    description: |
      Pull request comment.
      If this is set, a pull request comment is posted after a pull request is created.
    required: false
  project_owner:
    description: |
      Project owner where the pull request is added.
    required: false
  project_number:
    description: |
      Project number where the pull request is added.
    required: false
  milestone_number:
    description: |
      Milestone number where the pull request is added.
    required: false
  automerge_method:
    description: |
      auto-merge method. One of "merge", "squash", or "rebase".
      By default, auto-merge is disabled.
    required: false

  label:
    description: |
      Label name
    required: false
  config:
    description: config
    required: false
  config_file:
    description: File path to the config file
    required: false

  metadata_file:
    description: metadata file path
    required: false
  changed_files:
    description: A file that changed files are listed in
    required: false
  github_token:
    description: A GitHub access token
    required: false
  run_id:
    description: A workflow run id
    required: false
  allow_workflow_fix:
    description: |
      Either true or false. If true, the action allows the workflow to fix the code.
    required: false
    default: "false"
  workflow_name:
    description: |
      Client Workflow name. If this is empty, the action does not check the workflow name.
    required: false
    default: securefix
outputs: {}
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
