name: Bug Report
description: |
  Please report the bug of Server Action.
  If you're not sure if it's a bug or not, please use the template `Support Request` instead.
labels:
  - bug
body:
  - type: textarea
    id: version
    attributes:
      label: version
      value: |
        Versions that the issue occurs:

        (Opitonal) Versions that the issue doesn't occur:

    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce
      description: |
        Please see [the guide](https://github.com/suzuki-shunsuke/oss-contribution-guide#write-good-how-to-reproduce) too.
        workflow should be not partial but complete configuration.
        Please remove unnecessary code to reproduce the issue.
      value: |
        Workflow:

        ```yaml

        ```
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: Actual behaviour
    validations:
      required: true
  - type: textarea
    id: note
    attributes:
      label: Note
    validations:
      required: false
