name: Prepare for fixing code
description: Prepare for fixing code
inputs:
  app_id:
    description: |
      GitHub App ID
    required: true
  app_private_key:
    description: |
      GitHub App Private Key
    required: true
  workflow_name:
    description: |
      Client Workflow name. If this is empty, the action does not check the workflow name.
    required: false
    default: securefix
  allow_workflow_fix:
    description: |
      Either true or false. If true, the action allows the workflow to fix the code.
    required: false
    default: "false"
  config:
    description: |
      YAML config to push other repositories and branches.
    required: false
  config_file:
    description: |
      A file path to YAML config.
    required: false
  label_name:
    description: |
      Label name to trigger the action.
    required: false
    default: ${{github.event.label.name}}
  label_description:
    description: |
      Label description to trigger the action.
      The format must be <repository owner>/<repository name>/<workflow run ID>.
    required: false
    default: ${{github.event.label.description}}
  delete_label:
    description: |
      Either true or false. If true, the label is deleted.
    required: false
    default: "true"
  
outputs:
  pull_request:
    description: |
      Pull Request
    value: ${{steps.js.outputs.pull_request}}
  pull_request_number:
    description: |
      Pull Request number
    value: ${{steps.js.outputs.pull_request_number}}
  workflow_run:
    description: |
      Workflow Run
    value: ${{steps.js.outputs.workflow_run}}
  client_repository:
    description: |
      Repository Full Name
    value: ${{steps.js.outputs.repo_full_name}}
  push_repository:
    description: |
      Repository Full Name
    value: ${{steps.js.outputs.repository}}
  branch:
    description: |
      Branch
    value: ${{steps.js.outputs.branch}}
  create_pull_request:
    description: |
      Created pull request parameter
    value: ${{steps.js.outputs.create_pull_request}}
  workflow_run_id:
    description: |
      Workflow Run ID
    value: ${{steps.js.outputs.run_id}}
  metadata:
    description: |
      Metadata
    value: ${{steps.js.outputs.metadata}}
  fixed_files:
    description: |
      Fixed file paths
    value: ${{steps.js.outputs.fixed_files}}
  github_token:
    description: |
      GitHub App token
    value: ${{steps.js.outputs.github_token}}
  github_token_for_push:
    description: |
      GitHub App token to push a commit to the other repository
    value: ${{steps.js.outputs.github_token_for_push}}
  root_dir:
    description: |
      Root directory for commit-action
    value: ${{steps.js.outputs.root_dir}}
  automerge_method:
    description: |
      Automerge method for pull requests
    value: ${{steps.js.outputs.automerge_method}}
  project_owner:
    description: |
      Project owner for pull requests
    value: ${{steps.js.outputs.project_owner}}
  project_number:
    description: |
      Project number for pull requests
    value: ${{steps.js.outputs.project_number}}
runs:
  using: composite
  steps:
    - uses: csm-actions/securefix-action/js@main
      id: js
      with:
        action: prepare
        config: ${{inputs.config}}
        config_file: ${{inputs.config_file}}
        workflow_name: ${{inputs.workflow_name}}
        allow_workflow_fix: ${{inputs.allow_workflow_fix}}
        app_id: ${{inputs.app_id}}
        app_private_key: ${{inputs.app_private_key}}
        label_name: ${{inputs.label_name}}
        label_description: ${{inputs.label_description}}
        delete_label: ${{inputs.delete_label}}
