name: Create a commit
description: Create a commit
inputs:
  outputs:
    description: |
      Prepare action's outputs
    required: true
  commit_message:
    description: |
      Commit message
    required: false
    default: Securefix
runs:
  using: composite
  steps:
    # Create and push a commit
    - if: fromJson(inputs.outputs).fixed_files != ''
      id: commit
      uses: suzuki-shunsuke/commit-action@e3299afe2e5ffb76f1987743e3dbc0f00ece72d8 # v0.0.8
      with:
        github_token: ${{fromJson(inputs.outputs).github_token}}
        repository: ${{fromJson(inputs.outputs).push_repository}}
        branch: ${{fromJson(inputs.outputs).branch}}
        files: ${{fromJson(inputs.outputs).fixed_files}}
        commit_message: |
          ${{fromJson(fromJson(inputs.outputs).metadata).inputs.commit_message && fromJson(fromJson(inputs.outputs).metadata).inputs.commit_message || inputs.commit_message}}
          ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

    - shell: bash
      run: |
        echo "pushed: $PUSHED"
        echo "PR: $PR"
      env:
        PUSHED: ${{ steps.commit.outputs.pushed }}
        PR: ${{ toJson(fromJson(inputs.outputs).create_pull_request) }}

    # Create a pull request
    - if: (fromJson(inputs.outputs).fixed_files != '') && (steps.commit.outputs.pushed == 'true') && (fromJson(inputs.outputs).create_pull_request.title != '')
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      env:
        OUTPUTS: ${{ inputs.outputs }}
      with:
        github-token: ${{fromJson(inputs.outputs).github_token}}
        script: |
          const outputs = JSON.parse(process.env.OUTPUTS);
          const pr = await github.rest.pulls.create({
            owner: outputs.push_repository.split('/')[0],
            repo: outputs.push_repository.split('/')[1],
            head: outputs.branch,
            title: outputs.create_pull_request.title,
            body: outputs.create_pull_request.body,
            // base: fromJson(fromJson(inputs.outputs).workflow_run).base_branch,
            draft: outputs.create_pull_request.draft || false,
            labels: outputs.create_pull_request.labels || [],
            reviewers: outputs.create_pull_request.reviewers || [],
            assignees: outputs.create_pull_request.assignees || [],
          });
    # Create a pull request comment
