name: Create a commit
description: Create a commit
inputs:
  outputs:
    description: |
      Prepare action's outputs
    required: true
  commit_message:
    description: |
      Commit message
    required: false
    default: Securefix
runs:
  using: composite
  steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      id: commit-message
      env:
        METADATA: ${{fromJSON(inputs.outputs).metadata}}
        DEFAULT_COMMIT_MESSAGE: ${{inputs.commit_message}}
      with:
        result-encoding: string
        script: |
          const metadata = JSON.parse(process.env.METADATA);
          core.info(`Metadata: ${JSON.stringify(metadata)}`);
          return metadata.inputs.commit_message || process.env.DEFAULT_COMMIT_MESSAGE;

    # Create and push a commit
    - if: fromJSON(inputs.outputs).fixed_files != ''
      id: commit
      uses: suzuki-shunsuke/commit-action@87b297f0ce551411b43d1880f4fb3cbc60381055 # v0.0.14
      with:
        github_token: ${{fromJSON(inputs.outputs).github_token_for_push}}
        repository: ${{fromJSON(inputs.outputs).push_repository}}
        branch: ${{fromJSON(inputs.outputs).branch}}
        files: ${{fromJSON(inputs.outputs).fixed_files}}
        root_dir: ${{fromJSON(inputs.outputs).root_dir}}
        commit_message: |
          ${{steps.commit-message.outputs.result}}
          ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}

    # Create a pull request
    - if: |
        fromJSON(inputs.outputs).fixed_files &&
        (steps.commit.outputs.pushed == 'true') &&
        fromJSON(inputs.outputs).create_pull_request
      id: pr
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        OUTPUTS: ${{ inputs.outputs }}
      with:
        github-token: ${{fromJSON(inputs.outputs).github_token_for_push}}
        script: |
          const outputs = JSON.parse(process.env.OUTPUTS);
          const param = JSON.parse(outputs.create_pull_request);
          const owner = outputs.push_repository.split('/')[0];
          const repo = outputs.push_repository.split('/')[1];
          // Create a pull request
          const pr = await github.rest.pulls.create({
            owner: owner,
            repo: repo,
            head: outputs.branch,
            title: param.title,
            body: param.body,
            base: param.base,
            draft: param.draft || false,
          });
          core.notice(`Created a pull request: ${pr.data.html_url}`);
          // Create a pull request comment
          if (param.comment) {
            // Create a pull request comment
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: pr.data.number,
              body: param.comment,
            });
          }
          // Add labels
          if (param.labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: owner,
              repo: repo,
              issue_number: pr.data.number,
              labels: param.labels,
            });
          }
          // Add assignees
          if (param.assignees.length > 0) {
            await github.rest.issues.addAssignees({
              owner: owner,
              repo: repo,
              issue_number: pr.data.number,
              assignees: param.assignees,
            });
          }
          // Request reviews
          if (param.reviewers.length > 0 || param.team_reviewers.length > 0) {
            await github.rest.pulls.requestReviewers({
              owner: owner,
              repo: repo,
              pull_number: pr.data.number,
              reviewers: param.reviewers,
              team_reviewers: param.team_reviewers,
            });
          }
          // Set milestone
          if (param.milestone_number) {
            await github.rest.issues.update({
              owner: owner,
              repo: repo,
              issue_number: pr.data.number,
              milestone: param.milestone_number, // Set milestone
            });
          }
          return pr;

    - if: |
        steps.pr.outputs.result &&
        fromJSON(inputs.outputs).automerge_method
      shell: bash
      env:
        GH_TOKEN: ${{fromJSON(inputs.outputs).github_token_for_push}}
        PR_URL: ${{fromJSON(steps.pr.outputs.result && steps.pr.outputs.result || '{}').data.html_url}}
        REPOSITORY: ${{fromJSON(inputs.outputs).push_repository}}
        METHOD: "--${{fromJSON(inputs.outputs).automerge_method}}"
      run: |
        gh pr merge "$PR_URL" -R "$REPOSITORY" --auto "$METHOD"

    - if: |
        steps.pr.outputs.result &&
        fromJSON(inputs.outputs).project_owner
      shell: bash
      env:
        GH_TOKEN: ${{fromJSON(inputs.outputs).github_token_for_push}}
        PR_URL: ${{fromJSON(steps.pr.outputs.result && steps.pr.outputs.result || '{}').data.html_url}}
        OWNER: ${{fromJSON(inputs.outputs).project_owner}}
        NUMBER: ${{fromJSON(inputs.outputs).project_number}}
      run: |
        gh project item-add "$NUMBER" --owner "$OWNER" --url "$PR_URL"
