name: Create a commit
description: Create a commit
inputs:
  outputs:
    description: |
      Prepare action's outputs
    required: true
  commit_message:
    description: |
      Commit message
    required: false
    default: Securefix
runs:
  using: composite
  steps:
    # Create and push a commit
    - if: fromJson(inputs.outputs).fixed_files != ''
      uses: suzuki-shunsuke/commit-action@9faad521ea6a1e768439ffbe6b25b6cb3fc1b181 # v0.0.6
      with:
        github_token: ${{fromJson(inputs.outputs).github_token}}
        repository: ${{ fromJson(inputs.outputs).repository }}
        branch: ${{ fromJson(fromJson(inputs.outputs).workflow_run).head_branch }}
        files: ${{ fromJson(inputs.outputs).fixed_files }}
        commit_message: |
          ${{fromJson(fromJson(inputs.outputs).metadata).inputs.commit_message && fromJson(fromJson(inputs.outputs).metadata).inputs.commit_message || inputs.commit_message}}
          ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
