name: Create a commit
description: Create a commit
inputs:
  outputs:
    description: |
      Prepare action's outputs
    required: true
  commit_message:
    description: |
      Commit message
    required: false
    default: Securefix
runs:
  using: composite
  steps:
    - uses: csm-actions/securefix-action/js@main
      with:
        action: commit
        outputs: ${{inputs.outputs}}
        commit_message: ${{inputs.commit_message}}
