name: test (workflow_call)
permissions: {}
on: workflow_call
jobs:
  path-filter:
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json5
              - .github/workflows/workflow_call_test.yaml
              - .github/workflows/renovate-config-vdalidator.yaml

  renovate-config-validator:
    uses: ./.github/workflows/renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  typos:
    uses: ./.github/workflows/typos.yaml
    permissions: {}
